import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Suhaib's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-stone-900 text-stone-200 h-[5000px]`}
      >
        <div className="z-[-99] absolute ml-auto mr-auto left-0 right-0 w-full">
          <div className="flex justify-center">
            <div className="bg-[#31063479] blur-[5rem] top-[-6rem] h-[31.25rem] w-[31.25rem] rounded-full "></div>
            <div className="bg-[#06223479] blur-[5rem] top-[-6rem] h-[31.25rem] w-[31.25rem] rounded-full "></div>
          </div>
        </div>
        <Header />
        {children}
      </body>
    </html>
  );
}
